---
app_name: lokanhomepage
venv_dir: "/home/{{ username }}/.virtualenvs/{{ app_name }}"
code_dir: "/home/{{ username }}/development/{{ app_name }}"
req_path: "{{ code_dir }}/requirements/dev.txt"
repo_url: git@github.com:hakansund/lokanhomepage.git
secret_key: '2)_^$0(i=+zs05xm2cf@c*+62p^$_p261_j-^w^2$e=xls$q#m'
debug: True
template_debug: True
allowed_hosts: ['*']
extra_installed_apps: [debug_toolbar, defender]
extra_middleware_classes: [defender.middleware.FailedLoginMiddleware]
database_engine: "django.db.backends.postgresql_psycopg2"
database_name: "lokanhomepage"
database_user: "lokanhomepage"
database_password: "lokanhomepage"
database_host: "localhost"
database_port: ""
