---
- name: create static dir
  file:
    path: "{{ static_dir }}"
    state: directory
    owner: "{{ app_name }}"
    group: "{{ app_name }}"
    setype: httpd_sys_content_t

- name: collect the static files
  django_manage:
    app_path: "{{ code_dir }}"
    command: collectstatic
    settings: lokanhomepage.settings
    virtualenv: "{{ venv_dir }}"

- name: migrate database
  django_manage:
    app_path: "{{ code_dir }}"
    command: migrate
    settings: lokanhomepage.settings
    virtualenv: "{{ venv_dir }}"
