---
- name: create static dir
  file:
    path: "{{ static_dir }}"
    state: directory
    owner: "{{ app_name }}"
    group: "{{ app_name }}"

- name: collect the static files
  django_manage:
    app_path: "{{ code_dir }}"
    command: collectstatic
    settings: lokanhomepage.settings
    virtualenv: "{{ venv_dir }}"

- name: migrate database
  django_manage:
    app_path: "{{ code_dir }}"
    command: migrate auth
    settings: lokanhomepage.settings
    virtualenv: "{{ venv_dir }}"
  become: yes
  become_user: "{{ database_user }}"

- name: migrate database
  django_manage:
    app_path: "{{ code_dir }}"
    command: migrate
    settings: lokanhomepage.settings
    virtualenv: "{{ venv_dir }}"
  become: yes
  become_user: "{{ database_user }}"
