---
- name: ensure nginx is installed
  apt: name=nginx

- name: create nginx config
  template: src=nginx_site_config.j2 dest="/etc/nginx/sites-available/{{ app_name }}"

- name: enable nginx config
  file:
    path: "/etc/nginx/sites-enabled/{{ app_name }}"
    src: "/etc/nginx/sites-available/{{ app_name }}"
    state: link

- name: remove default nginx config
  file: path="/etc/nginx/sites-enabled/default" state=absent

- name: reload and enable nginx
  service: name=nginx state=reloaded enabled=yes
