---
- name: ensure postgresql is installed
  apt: name={{ item }}
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2
    - python3-psycopg2

- name: create postgres user
  postgresql_user: name={{ database_user }} password={{ database_password }}
  become: yes
  become_user: postgres

- name: create database
  postgresql_db: name={{ database_name }} owner={{ database_user }}
  become: yes
  become_user: postgres
