---
- name: disallow ssh password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present

- name: reload sshd
  service: name=ssh state=reloaded
