---
- name: fetch source code
  git: dest="{{ code_dir }}" repo="{{ repo_url }}" accept_hostkey=yes

- name: update yamjam config
  template:
    src: ../../dev/templates/config.yaml.j2
    dest: "{{ code_dir }}/config.yaml"

- name: install requirements in virtual environment
  pip: requirements="{{ req_path }}" virtualenv="{{ venv_dir }}" state=latest

- name: migrate database
  django_manage:
    app_path: "{{ code_dir }}"
    command: migrate
    settings: lokanhomepage.settings
    virtualenv: "{{ venv_dir }}"
