---
- name: create yamjam config
  template: src=config.yaml.j2 dest="{{ code_dir }}/config.yaml"

- name: migrate database
  django_manage:
    app_path: "{{ code_dir }}"
    command: migrate
    settings: lokanhomepage.settings
    virtualenv: "{{ venv_dir }}"
