---
- name: ensure postgresql is installed
  dnf: name={{ item }}
  with_items:
    - postgresql-server
    - postgresql-devel
    - python-psycopg2
  become: yes

- name: initiate database
  command: postgresql-setup initdb
  args:
    creates: /var/lib/pgsql/data/postgresql.conf
  become: yes

- name: create postgresql config
  template: src=pg_hba.conf.j2 dest=/var/lib/pgsql/data/pg_hba.conf
  become: yes

- name: start postgresql
  service: name=postgresql state=started enabled=yes
  become: yes

- name: create postgres user
  postgresql_user:
    name: "{{ database_user }}"
    password: "{{ database_password }}"
    role_attr_flags: CREATEDB
  become: yes
  become_user: postgres

- name: create database
  postgresql_db: name="{{ database_name }}" owner="{{ database_user }}"
  become: yes
  become_user: postgres
